services:
  - type: web
    name: yt-downloader-backend
    env: node
    region: singapore
    plan: starter
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y python3 python3-pip ffmpeg
      pip3 install --upgrade pip
      pip3 install yt-dlp
      npm install
      npm run build
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: localhost:5173
      - key: DOWNLOAD_DIR
        value: /opt/render/project/src/downloads
      - key: LOG_FILE
        value: /opt/render/project/src/logs/app.log

databases:
  - name: redis
    databaseName: redis
    plan: free
    # type: redis

