[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "python3", "ffmpeg"]

[phases.install]
cmds = [
  "pip3 install --upgrade pip",
  "pip3 install yt-dlp",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

